dist:
  name: otelcol-snowflake
  description: Basic OTel Collector distribution for Developers
  output_path: .
  otelcol_version: 0.100.0

exporters:
  - gomod:
      go.opentelemetry.io/collector/exporter/debugexporter v0.100.0
  - gomod:
      go.opentelemetry.io/collector/exporter/otlpexporter v0.100.0
  - gomod:
      go.opentelemetry.io/collector/exporter/loggingexporter v0.100.0

processors:
  - gomod:
      go.opentelemetry.io/collector/processor/batchprocessor v0.100.0
  - gomod:
      go.opentelemetry.io/collector/processor/memorylimiterprocessor v0.100.0

extensions:
  - gomod:
      github.com/open-telemetry/opentelemetry-collector-contrib/extension/healthcheckextension v0.100.0


receivers:
  - gomod:
      github.com/open-telemetry/opentelemetry-collector-contrib/receiver/sqlqueryreceiver v0.100.0
  - gomod:
      go.opentelemetry.io/collector/receiver/otlpreceiver v0.100.0
