dist:
  name: otelcol-snowflake
  description: Basic OTel Collector distribution for Developers
  output_path: .
  otelcol_version: 0.91.0

exporters:
  - gomod:
      go.opentelemetry.io/collector/exporter/debugexporter v0.91.0
  - gomod:
      go.opentelemetry.io/collector/exporter/otlpexporter v0.91.0

processors:
  - gomod:
      go.opentelemetry.io/collector/processor/batchprocessor v0.91.0

receivers:
  - gomod:
      github.com/open-telemetry/opentelemetry-collector-contrib/receiver/sqlqueryreceiver v0.91.0
